# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b0c6c25e613826198d788dea1b5c30134cf984e60dbc198d1e71c1888b94f36141917ba169e1d2e152564b2fc355e2c53c77cac7659267807fdfa4c319e78cd

test:
  secret_key_base: cbdc505c3004307f5564a349a0b98fcdfa96e15992ed66a68a2cbfbba57875fc7ab0e195513c2b8135530fd5672bb4b7679a8c19333540c944567ec22e479994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
